loglevel: info

database:
  host: db.example.com
  user: foo
  password: xxxx
  database: gearr
  sslmode: disable

web:
  token: encoding123

scheduler:
  downloadPath: /source
  uploadPath: /target
  domain: http://gearr.example.com

scanner:
  enabled: false
  interval: 24h
  minFileSize: 100000000
  paths:
    - /media/movies
    - /media/tvshows
  fileExtensions:
    - .mkv
    - .mp4
    - .avi
    - .mov
