loglevel: info

database:
  host: db.example.com
  user: foo
  password: xxxx
  database: gearr
  sslmode: disable

web:
  token: encoding123

scheduler:
  downloadPath: /source
  uploadPath: /target
  domain: http://gearr.example.com