loglevel: info

database:
  host: db.example.com
  user: foo
  password: xxxx
  # schema -> database name
  scheme: orchestrator
  sslmode: disable

web:
  token: encoding123

broker:
  host: 127.0.0.1
  user: encoding123
  password: xxxxx
  taskEncodeQueue: tasks
  taskPGSQueue: tasks_pgstosrt
  eventQueue: task_events

scheduler:
  downloadPath: /source
  uploadPath: /target
  domain: http://gearr.example.com
