version: "3"

services:
  server:
    image: ghcr.io/pando85/gearr:latest-server
    environment:
      LOG_LEVEL: DEBUG
      BROKER_HOST: rabbitmq
      BROKER_USER: rabbit
      BROKER_PASSWORD: rabbit_password
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres_password
      DATABASE_DATABASE: gearr
      SCHEDULER_DOMAIN: http://server:8080
      SCHEDULER_MINFILESIZE: "100"
      WEB_TOKEN: super-secret-token
    volumes:
      - ./demo-files:/data/current:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gearr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit_password
    ports:
      - "5672:5672"

  worker:
    image: ghcr.io/pando85/gearr:latest-worker
    command:
      - --log-level
      - debug
      - --broker.host
      - rabbitmq
      - --broker.user
      - rabbit
      - --broker.password
      - rabbit_password
      - --worker.acceptedJobs
      - encode
      - --worker.pgsJobs
      - "1"
      - --worker.maxPrefetchJobs
      - "3"
    depends_on:
      - rabbitmq
      - server

  worker-pgs:
    image: ghcr.io/pando85/gearr:latest-worker-pgs
    command:
      - --log-level
      - debug
      - --broker.host
      - rabbitmq
      - --broker.user
      - rabbit
      - --broker.password
      - rabbit_password
      - --worker.pgsJobs
      - "1"
      - --worker.acceptedJobs
      - pgstosrt
    depends_on:
      - rabbitmq
      - server
