version: "3"

services:
  server:
    image: ${IMAGE_NAME:-ghcr.io/pando85/gearr}:${IMAGE_VERSION:-latest}-server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    restart: on-failure
    environment:
      LOG_LEVEL: DEBUG
      DATABASE_DRIVER: pgx
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres_password
      DATABASE_DATABASE: gearr
      SCHEDULER_DOMAIN: http://server:8080
      SCHEDULER_MINFILESIZE: "10000000"
      WEB_TOKEN: super-secret-token
    volumes:
      - ./demo-files:/data/current:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gearr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  worker:
    image: ${IMAGE_NAME:-ghcr.io/pando85/gearr}:${IMAGE_VERSION:-latest}-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    restart: on-failure
    command:
      - --log-level
      - debug
      - --database.host
      - postgres
      - --database.user
      - postgres
      - --database.password
      - postgres_password
      - --database.database
      - gearr
      - --worker.acceptedJobs
      - encode
      - --worker.pgsJobs
      - "1"
      - --worker.maxPrefetchJobs
      - "3"
    depends_on:
      - postgres
      - server

  worker-pgs:
    image: ${IMAGE_NAME:-ghcr.io/pando85/gearr}:${IMAGE_VERSION:-latest}-worker-pgs
    build:
      context: .
      dockerfile: Dockerfile
      target: worker-pgs
    restart: on-failure
    command:
      - --log-level
      - debug
      - --database.host
      - postgres
      - --database.user
      - postgres
      - --database.password
      - postgres_password
      - --database.database
      - gearr
      - --worker.pgsJobs
      - "1"
      - --worker.acceptedJobs
      - pgstosrt
    depends_on:
      - postgres
      - server
