version: '3'

services:
  server:
    image: pando85/transcoder:latest-server
    environment:
      BROKER_HOST: rabbitmq
      BROKER_USER: rabbit
      BROKER_PASSWORD: rabbit_password
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres_password
      DATABASE_DATABASE: transcoder
      SCHEDULER_DOMAIN: http://server:8080
      WEB_TOKEN: super-secret-token
    volumes:
      - ./demo-files:/data/current:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: transcoder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit_password
    ports:
      - "5672:5672"

  worker:
    image: pando85/transcoder:latest-worker
    command:
      - --broker.host
      - rabbitmq
      - --broker.user
      - rabbit
      - --broker.password
      - rabbit_password
      - --worker.priority
      - "9"
    depends_on:
      - rabbitmq
      - server
